### ISSUE TITLE
TypeError in thermal_model.py

### ISSUE THREAD

**Issue by MakisH** [philipp007/masters_thesis#5]
When trying to run `thermal_model.py`, I get the following error:

```
vagrant@precicevm:~/Desktop/masters_thesis/thermal$ python3 thermal_model.py 

Traceback (most recent call last):
  File "thermal_model.py", line 44, in <module>
    cells={"tetra": msh.cells["tetra"]}))
TypeError: list indices must be integers or slices, not str
```

I have no experience with `meshio`. This is the respective code:

https://github.com/philipp007/masters_thesis/blob/ed908330824ee0a4ef18ddaf831505c0c15f3f4e/thermal/thermal_model.py#L41-L44

I am using meshio 5.3.4 from PIP, with Python 3.8.10. Same on another system with Ubuntu 22.04 and Python 3.10.12.

@philipp007 any ideas on what could be wrong?

**Comment by philipp007** [comment]
I'm 100% sure, that this worked on KBs ubuntu Laptop. 
My best guess is, that there is some version conflict. Unfortunately I don't know what version of meshio I used and how to resolve this. 
Now I learn, that I should have prioritized the documentation and creating a container during the working time. 
Sorry, I honestly didn't know that.

**Comment by MakisH** [comment]
After resolving #4, I get the same issue in the electrostatic model as well:

```
vagrant@precicevm:~/Desktop/masters_thesis/electrostatics$ python3 electrostatic_model.py 
/home/vagrant/Desktop/masters_thesis/electrostatics/../utilities/battery_properties.py:192: UserWarning: cell values are being extrapolated reasonably due to low C-rate
  warnings.warn("cell values are being extrapolated reasonably due to low C-rate")

Traceback (most recent call last):
  File "electrostatic_model.py", line 72, in <module>
    meshio.write("dolfin_files/mesh.xdmf", meshio.Mesh(points=msh.points, cells={"tetra": msh.cells["tetra"]}))
TypeError: list indices must be integers or slices, not str
```

Trying different meshio versions:

- 5.3.4 leads to this error
- 5.3.0 ([included in Ubuntu 22.04](https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=meshio)): same
- 5.3.0 from APT (`python3-meshio`): same
- 4.0.0: same
- 3.0.0 and 2.0.0: cannot run at all, due to linking issues to HDF5

**Comment by MakisH** [comment]
This thread from the FEniCS forum seems related: https://fenicsproject.discourse.group/t/transitioning-from-mesh-xml-to-mesh-xdmf-from-dolfin-convert-to-meshio/412/101?page=7

**Comment by philipp007** [comment]
Thanks for trying different versions. 
Sorry but I have no idea what the problem could be. And I don't have a computer to test this myself.
